-- Statements to undo demonstration database

DROP INDEX DEMO.FK_CustomerID_ID2#
DROP INDEX DEMO.FK_ProductID_ID#
DROP INDEX DEMO.FK_ID_ID#
DROP INDEX DEMO.FK_SalesRepresentative_EmployeeID#
DROP INDEX DEMO.FK_FinancialCode_Code#
DROP INDEX DEMO.FK_CustomerID_ID#
DROP INDEX DEMO.FK_Code_Code#
DROP INDEX DEMO.ProductsIX#

DELETE FROM DEMO.Contacts#
DELETE FROM DEMO.SalesOrderItems#
DELETE FROM DEMO.SalesOrders#
DELETE FROM DEMO.Customers#
DELETE FROM DEMO.Products#
DELETE FROM DEMO.FinancialData#
DELETE FROM DEMO.FinancialCodes#
UPDATE DEMO.Departments SET DepartmentHead = NULL#
DELETE FROM DEMO.Employees#
DELETE FROM DEMO.Departments#

DROP PROCEDURE DEMO.ShowProductInfo CASCADE#
DROP VIEW DEMO.ViewSalesOrders#
DROP TABLE DEMO.Contacts CASCADE#
DROP TABLE DEMO.SalesOrderItems CASCADE#
DROP TABLE DEMO.SalesOrders CASCADE#
DROP TABLE DEMO.Customers CASCADE#
DROP TABLE DEMO.Products CASCADE#
DROP TABLE DEMO.FinancialData CASCADE#
DROP TABLE DEMO.FinancialCodes CASCADE#
DROP TABLE DEMO.Departments CASCADE#
DROP TABLE DEMO.Employees CASCADE#

DROP SCHEMA DEMO CASCADE#
